### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by Manliketjb** [Mojito-Fivem/mojito_dialogue#1]
keep on punching the ped after the interaction has ended. After clicking "yes" or "no" you punch the ped

**Comment by Mojito-Fivem** [comment]
Little Info

**Comment by Manliketjb** [comment]
> Little Info

meaning???... it's pretty self explanatory. LAlt the ped > talk to npc > click yes or no = punch ped....

Controls are not disabled properly when talking to the ped.... or they disable at the wrong time making you punch the mpc when picking your selection

**Comment by Mojito-Fivem** [comment]
Then PR if you know the issue

**Comment by Manliketjb** [comment]
Not my pig, not my farm...

**Comment by Mojito-Fivem** [comment]
My repo, my lack of fucks to give
